AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Sales Outreach Agent – Hackathon demo (API Gateway + Lambdas + DynamoDB + Bedrock)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 25
    MemorySize: 512
    Environment:
      Variables:
        EMAIL_DRY_RUN: "1"
        SEARCH_DRY_RUN: "1"
        LEADS_TABLE_NAME: !Ref LeadsTable
        SES_FROM_EMAIL: ""
        BEDROCK_MODEL_ID: "us.amazon.nova-pro-v1:0"
        BEDROCK_REGION: !Ref BedrockRegion
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Parameters:
  FromEmail:
    Type: String
    Default: ""
    Description: Default SES sender (verified address)
  BedrockRegion:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-central-1
    Description: Region where Bedrock is enabled for your account

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  LeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  SearchShopify:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_functions/search_shopify_retailers.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeadsTable
      Events:
        PostSearch:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /search
            Method: post

  StoreLead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_functions/store_lead_data.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeadsTable
      Events:
        PostStore:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /leads
            Method: post

  UpdateLeadStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_functions/update_lead_status.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeadsTable
      Events:
        PostUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /leads/status
            Method: post

  SendEmail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_functions/send_cold_email.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Environment:
        Variables:
          SES_FROM_EMAIL: !Ref FromEmail
      Events:
        PostEmail:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /email/send
            Method: post

  DraftEmail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_functions/bedrock_email_draft.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
        - DynamoDBReadPolicy:
            TableName: !Ref LeadsTable
      Events:
        PostDraft:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /email/draft
            Method: post

Outputs:
  ApiUrl:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  LeadsTableName:
    Value: !Ref LeadsTable
